from .feedforward import FeedforwardClassificationBackbone, FeedforwardClassificationBackboneConfig
from .convolutional import ConvolutionalClassificationBackbone, ConvolutionalClassificationBackboneConfig
